name: chasham_fyp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: NooriNastaliq
      fonts:
        - asset: assets/fonts/Noori-Nastaliq.ttf
          weight: 700
    
    - family: NastaliqKasheeda
      fonts:
        - asset: assets/fonts/Nastaliq-Kasheeda.ttf
          weight: 700

    - family: SameerQamri
      fonts:
        - asset: assets/fonts/Sameer-Qamri.ttf
          weight: 700
    
    - family: Aasar
      fonts:
        - asset: assets/fonts/Aasar.ttf
          weight: 700
    

  